[package]
name = "logmerger"
version = "1.0.0"
authors = ["monmaru"]
description = "CLI tool for merge log files"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
chrono = "0.4"
ansi_term = "0.12.1"