[package]
name = "logmerger"
version = "0.1.0"
authors = ["monmaru"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
chrono = "0.4"
